// Code generated by protoc-gen-go. DO NOT EDIT.
// source: redeam-rest.proto

/*
Package v1 is a generated protocol buffer package.

It is generated from these files:
	redeam-rest.proto

It has these top-level messages:
	Book
	CreateRequest
	CreateResponse
	ReadRequest
	ReadResponse
	UpdateRequest
	UpdateResponse
	DeleteRequest
	DeleteResponse
	ReadAllRequest
	ReadAllResponse
*/
package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Book_Status int32

const (
	Book_UNKNOWN     Book_Status = 0
	Book_CHECKED_IN  Book_Status = 1
	Book_CHECKED_OUT Book_Status = 2
)

var Book_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "CHECKED_IN",
	2: "CHECKED_OUT",
}
var Book_Status_value = map[string]int32{
	"UNKNOWN":     0,
	"CHECKED_IN":  1,
	"CHECKED_OUT": 2,
}

func (x Book_Status) String() string {
	return proto.EnumName(Book_Status_name, int32(x))
}
func (Book_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// Books the library has
type Book struct {
	Id          int64                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title       string                     `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Author      string                     `protobuf:"bytes,3,opt,name=author" json:"author,omitempty"`
	Publisher   string                     `protobuf:"bytes,4,opt,name=publisher" json:"publisher,omitempty"`
	PublishDate *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=publish_date,json=publishDate" json:"publish_date,omitempty"`
	Rating      float64                    `protobuf:"fixed64,6,opt,name=rating" json:"rating,omitempty"`
	Status      Book_Status                `protobuf:"varint,7,opt,name=status,enum=v1.Book_Status" json:"status,omitempty"`
}

func (m *Book) Reset()                    { *m = Book{} }
func (m *Book) String() string            { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()               {}
func (*Book) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Book) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Book) GetPublisher() string {
	if m != nil {
		return m.Publisher
	}
	return ""
}

func (m *Book) GetPublishDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.PublishDate
	}
	return nil
}

func (m *Book) GetRating() float64 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *Book) GetStatus() Book_Status {
	if m != nil {
		return m.Status
	}
	return Book_UNKNOWN
}

type CreateRequest struct {
	Api  string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	Book *Book  `protobuf:"bytes,2,opt,name=book" json:"book,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateRequest) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type CreateResponse struct {
	Api string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	Id  int64  `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReadRequest struct {
	Api string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	Id  int64  `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReadResponse struct {
	Api  string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	Book *Book  `protobuf:"bytes,2,opt,name=book" json:"book,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadResponse) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type UpdateRequest struct {
	Api  string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	Book *Book  `protobuf:"bytes,2,opt,name=book" json:"book,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpdateRequest) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type UpdateResponse struct {
	Api     string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	Updated int64  `protobuf:"varint,2,opt,name=updated" json:"updated,omitempty"`
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpdateResponse) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type DeleteRequest struct {
	Api string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	Id  int64  `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DeleteRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteResponse struct {
	Api     string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	Deleted int64  `protobuf:"varint,2,opt,name=deleted" json:"deleted,omitempty"`
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DeleteResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteResponse) GetDeleted() int64 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

type ReadAllRequest struct {
	Api string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
}

func (m *ReadAllRequest) Reset()                    { *m = ReadAllRequest{} }
func (m *ReadAllRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadAllRequest) ProtoMessage()               {}
func (*ReadAllRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ReadAllRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type ReadAllResponse struct {
	Api   string  `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	Books []*Book `protobuf:"bytes,2,rep,name=books" json:"books,omitempty"`
}

func (m *ReadAllResponse) Reset()                    { *m = ReadAllResponse{} }
func (m *ReadAllResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadAllResponse) ProtoMessage()               {}
func (*ReadAllResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ReadAllResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadAllResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

func init() {
	proto.RegisterType((*Book)(nil), "v1.Book")
	proto.RegisterType((*CreateRequest)(nil), "v1.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "v1.CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "v1.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "v1.ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "v1.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "v1.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "v1.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "v1.DeleteResponse")
	proto.RegisterType((*ReadAllRequest)(nil), "v1.ReadAllRequest")
	proto.RegisterType((*ReadAllResponse)(nil), "v1.ReadAllResponse")
	proto.RegisterEnum("v1.Book_Status", Book_Status_name, Book_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BookService service

type BookServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	ReadAll(ctx context.Context, in *ReadAllRequest, opts ...grpc.CallOption) (*ReadAllResponse, error)
}

type bookServiceClient struct {
	cc *grpc.ClientConn
}

func NewBookServiceClient(cc *grpc.ClientConn) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := grpc.Invoke(ctx, "/v1.BookService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := grpc.Invoke(ctx, "/v1.BookService/Read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := grpc.Invoke(ctx, "/v1.BookService/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := grpc.Invoke(ctx, "/v1.BookService/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) ReadAll(ctx context.Context, in *ReadAllRequest, opts ...grpc.CallOption) (*ReadAllResponse, error) {
	out := new(ReadAllResponse)
	err := grpc.Invoke(ctx, "/v1.BookService/ReadAll", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BookService service

type BookServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	ReadAll(context.Context, *ReadAllRequest) (*ReadAllResponse, error)
}

func RegisterBookServiceServer(s *grpc.Server, srv BookServiceServer) {
	s.RegisterService(&_BookService_serviceDesc, srv)
}

func _BookService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.BookService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.BookService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.BookService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.BookService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_ReadAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).ReadAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.BookService/ReadAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).ReadAll(ctx, req.(*ReadAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _BookService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _BookService_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _BookService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BookService_Delete_Handler,
		},
		{
			MethodName: "ReadAll",
			Handler:    _BookService_ReadAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "redeam-rest.proto",
}

func init() { proto.RegisterFile("redeam-rest.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 515 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x4e, 0xe2, 0x90, 0x71, 0xe3, 0xb8, 0x0b, 0x42, 0x96, 0x55, 0x81, 0xe5, 0x0b, 0xe6,
	0x80, 0xad, 0x18, 0x89, 0x53, 0xa1, 0x82, 0xa4, 0x12, 0xa8, 0x52, 0x2a, 0xb9, 0x8d, 0x38, 0x56,
	0x1b, 0xbc, 0xa4, 0x56, 0x9d, 0xae, 0xb1, 0xd7, 0xf9, 0x31, 0xfc, 0x59, 0x90, 0xf7, 0xa3, 0xa9,
	0x23, 0x9c, 0x4b, 0x6f, 0x79, 0xcf, 0x33, 0xf3, 0xde, 0xbe, 0x99, 0xc0, 0x71, 0x49, 0x52, 0x82,
	0x37, 0xef, 0x4b, 0x52, 0xb1, 0xb0, 0x28, 0x29, 0xa3, 0x48, 0xdf, 0x4e, 0xdd, 0x37, 0x6b, 0x4a,
	0xd7, 0x39, 0x89, 0x38, 0xb3, 0xaa, 0x7f, 0x45, 0x2c, 0xdb, 0x90, 0x8a, 0xe1, 0x4d, 0x21, 0x8a,
	0xfc, 0x3f, 0x3a, 0xf4, 0xbf, 0x52, 0x7a, 0x87, 0x2c, 0xd0, 0xb3, 0xd4, 0xd1, 0x3c, 0x2d, 0xe8,
	0x25, 0x7a, 0x96, 0xa2, 0x97, 0x30, 0x60, 0x19, 0xcb, 0x89, 0xa3, 0x7b, 0x5a, 0x30, 0x4a, 0x04,
	0x40, 0xaf, 0xc0, 0xc0, 0x35, 0xbb, 0xa5, 0xa5, 0xd3, 0xe3, 0xb4, 0x44, 0xe8, 0x04, 0x46, 0x45,
	0xbd, 0xca, 0xb3, 0xea, 0x96, 0x94, 0x4e, 0x9f, 0x7f, 0xda, 0x11, 0xe8, 0x13, 0x1c, 0x49, 0x70,
	0x93, 0x62, 0x46, 0x9c, 0x81, 0xa7, 0x05, 0x66, 0xec, 0x86, 0xc2, 0x5c, 0xa8, 0xcc, 0x85, 0xd7,
	0xca, 0x5c, 0x62, 0xca, 0xfa, 0x39, 0x66, 0x5c, 0xb4, 0xc4, 0x2c, 0xbb, 0x5f, 0x3b, 0x86, 0xa7,
	0x05, 0x5a, 0x22, 0x11, 0x7a, 0x0b, 0x46, 0xc5, 0x30, 0xab, 0x2b, 0x67, 0xe8, 0x69, 0x81, 0x15,
	0x4f, 0xc2, 0xed, 0x34, 0x6c, 0x1e, 0x13, 0x5e, 0x71, 0x3a, 0x91, 0x9f, 0xfd, 0x8f, 0x60, 0x08,
	0x06, 0x99, 0x30, 0x5c, 0x2e, 0x2e, 0x16, 0x97, 0x3f, 0x16, 0xf6, 0x33, 0x64, 0x01, 0xcc, 0xbe,
	0x9d, 0xcf, 0x2e, 0xce, 0xe7, 0x37, 0xdf, 0x17, 0xb6, 0x86, 0x26, 0x60, 0x2a, 0x7c, 0xb9, 0xbc,
	0xb6, 0x75, 0xff, 0x0c, 0xc6, 0xb3, 0x92, 0x60, 0x46, 0x12, 0xf2, 0xbb, 0x26, 0x15, 0x43, 0x36,
	0xf4, 0x70, 0x91, 0xf1, 0x94, 0x46, 0x49, 0xf3, 0x13, 0x9d, 0x40, 0x7f, 0x45, 0xe9, 0x1d, 0x4f,
	0xc9, 0x8c, 0x9f, 0x2b, 0x07, 0x09, 0x67, 0xfd, 0x18, 0x2c, 0x35, 0xa0, 0x2a, 0xe8, 0x7d, 0x45,
	0xfe, 0x33, 0x41, 0x04, 0xaf, 0xab, 0xe0, 0xfd, 0x08, 0xcc, 0x84, 0xe0, 0xb4, 0x5b, 0x72, 0xbf,
	0xe1, 0x33, 0x1c, 0x89, 0x86, 0x4e, 0x89, 0xc3, 0x26, 0xcf, 0x60, 0xbc, 0x2c, 0xd2, 0x27, 0xbc,
	0xf2, 0x14, 0x2c, 0x35, 0xa0, 0xd3, 0x82, 0x03, 0xc3, 0x9a, 0xd7, 0x28, 0xe7, 0x0a, 0xfa, 0x53,
	0x18, 0xcf, 0x49, 0x4e, 0x0e, 0xc9, 0xef, 0xbf, 0xf8, 0x14, 0x2c, 0xd5, 0x72, 0x48, 0x30, 0xe5,
	0x35, 0x0f, 0x82, 0x12, 0xfa, 0x3e, 0x58, 0x4d, 0x5e, 0x5f, 0xf2, 0xbc, 0x53, 0xd1, 0x9f, 0xc1,
	0xe4, 0xa1, 0xa6, 0x53, 0xe2, 0x35, 0x0c, 0x9a, 0xf7, 0x57, 0x8e, 0xee, 0xf5, 0x5a, 0xb1, 0x08,
	0x3a, 0xfe, 0xab, 0x81, 0xd9, 0xe0, 0x2b, 0x52, 0x6e, 0xb3, 0x9f, 0x04, 0x45, 0x60, 0x88, 0x6b,
	0x40, 0xc7, 0x4d, 0x69, 0xeb, 0xb4, 0x5c, 0xf4, 0x98, 0x92, 0x92, 0xef, 0xa0, 0xdf, 0xb8, 0x40,
	0xfc, 0xb0, 0x1f, 0x1d, 0x85, 0x6b, 0xef, 0x08, 0x59, 0x1a, 0x81, 0x21, 0x76, 0x20, 0x66, 0xb7,
	0x16, 0x2a, 0x66, 0xef, 0xad, 0x28, 0x02, 0x43, 0x64, 0x28, 0x1a, 0x5a, 0x2b, 0x10, 0x0d, 0x7b,
	0x11, 0xc7, 0x30, 0x94, 0x91, 0x20, 0xa4, 0xe4, 0x77, 0x19, 0xba, 0x2f, 0x5a, 0x9c, 0xe8, 0x59,
	0x19, 0xfc, 0xaf, 0xfd, 0xe1, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x44, 0x00, 0xba, 0x09, 0x9e,
	0x04, 0x00, 0x00,
}
